language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
jobs:
  include:
    - stage: pex
      script: ./build.sh
      deploy:
        provider: releases
        api_key:
          secure: I6rrrOWsEvXHp4HtBo/NZBVVtxILgCebbblv1hTwcp+xAGnZIPbY9j8G094yvpIb4JLp81pJISAux6gK6Q0pdV8skeL9bmQ1tPSPZBmat1Ic3QlourqEf0vlK965stZo4TACK0SV740bCkEezZxkFUIB42yzkL1/Qh0vdAgbWvDPXFSchJihXRKuilm8FNr9InZNfGaQpUG24EjP4fGP1gtUcMCxgV4GBh3pwA80PdwtROLO9xG4YSNunZ8Jy4DM0Si0EHIo0OEI51DehFHGCy/3elUAHg5V7DXh7pgGf0KatlI3P5m/x4dZuKB7M4TEZRTDUsmWpbxhyiTWwEEdCD09pZuWQ6eBdZ6pdpg0jaoTrnDj0IobdXlE8OIUFVsFMdZR+8XV4kRjUJPukGgJxU3EWqdl7nK7lqxitmDSAyJHdLC598OQPlRWu1cdWUY9ienL18OvGBvfLgvEJuCHIJN/qiwsvqFJUr9CFFjfw6DXhf8MwU1ft7DCKc7VVFc7UiROP6Gryj31/A7n2XmUKlqY7Xq1zcxzHKRHzTJbWyv8PmfED5xio1aEh5FDGwq0l0jdGUy5NwWrUUijSIM0KeiD0Ish7Nh1pZcycnSgiEKw16Vd0Szx9QHUWjM+WT8MFuriD2h4euHQyrSWKeef+7TRkKa2NwaCo7Sm1O/tpGk=
        file: whim
        skip_cleanup: true
        on:
          repo: Sibilance/whim
          tags: true
    - stage: pypi
      script: python3 setup.py sdist bdist_wheel
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: "hZ78FfY0TW45P6UmiGo2u2pMIn3VcbX9TLTgk4Ttmu8gMWY3smpHLukFpg4QTLFm87xqqwG5SyzCa9FpGNUSDGuMBliy6QkabbVbRc9ex5N5q4JXxl+y7YBxWBejyawt3bqoLpzvCkHLPT+y4S86nXiJPwyHMtSbVz/hLbWYWoRFm761Mc7Ap1rO6cMY34kVqhO5omrr4666i9tyCDzGYBI52R7NioGaEaUIkW9U03GN0NoSElivD2WiokmTqU4snaTCo6h5r7w5eOPGxP+Q6lwoeDju892FKa7EHVnyXHxVR4tETasD0LG9sFdH4VgYzJrucPquVYv7uYKwonPQV21YV2BXJkg1XVuDLulpwI3+iJc6XZFI2X9feONulf6P5N/cV2jOTszGEW77/c9yN9MWqgKLqBAv5IbimP+SpS/Ywn9s0HOu8yirWu43XdtZXpQpkKQzgnnECNmBgDZ5kdSDQ+JH1pt4ViwaGIBrhxwZBD5UjY0Dz5nZgEKGrUSLWTjx2YQgNCsAnrucOgm0hbJM4svmRKO4NGVEJIf9XbDNbxb74ZRyZvn2kx/55t+ckEP8Cnfrv996Gh07mcgqd3IGwU5/opw2jiyoouDEBeie8dfE7Kxf8LWju0sXnrdx++FkKpnZg+2m/FKogQWvTJoygTviaB1FJZqD+a+lFc8="
